language: "python"
python: "3.6"
sudo: required
addons:
  apt:
    update: true
    sources:
    - debian-sid
install:
  - sudo apt install openssh curl -y
  - curl http://myip.dnsomatic.com
  - printf '\nwexler-qc750\n\nnone\n\n\n' | ./pmbootstrap.py init
  - ./pmbootstrap.py --details-to-stdout install
notifications:
  - email: false
