language: "python"
python: "3.6"
sudo: required
addons:
  apt:
    update: true
    sources:
    - debian-sid
install:
  - printf '\nwexler-qc750\n\nnone\n\n\n' | ./pmbootstrap.py init
  - printf 'user\nuser\n\n' | ./pmbootstrap.py --details-to-stdout install
  - sudo .travis/upload-build.sh
notifications:
  - email: false
